apiVersion: v1
kind: Namespace
metadata:
  name: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-latency-monitor
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-latency-monitor
  template:
    metadata:
      labels:
        app: api-latency-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: api-latency-monitor
        image: rocordemu/api-latency-monitor:latest
        ports:
        - containerPort: 8000
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-token
              key: token
        - name: POLL_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: api-latency-monitor-config
              key: POLL_INTERVAL
        - name: API_URL_1
          valueFrom:
            configMapKeyRef:
              name: api-latency-monitor-config
              key: API_URL_1
        - name: API_URL_2
          valueFrom:
            configMapKeyRef:
              name: api-latency-monitor-config
              key: API_URL_2
        - name: API_URL_3
          valueFrom:
            configMapKeyRef:
              name: api-latency-monitor-config
              key: API_URL_3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: db-storage
          mountPath: /app/status.db
      volumes:
      - name: db-storage
        emptyDir: {}