apiVersion: v1
kind: Service
metadata:
  name: api-latency-monitor
  namespace: monitoring-project
spec:
  selector:
    app: api-latency-monitor
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort