apiVersion: v1
kind: Service
metadata:
  name: api-latency-monitor
spec:
  selector:
    app: api-latency-monitor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP