
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-app-1
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app/logs # This is where logs are stored on the node
    type: DirectoryOrCreate
  storageClassName: ""  # Explicitly setting storageClassName to empty string
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-app-2
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app/logs # This is where logs are stored on the node
    type: DirectoryOrCreate
  storageClassName: ""  # Explicitly setting storageClassName to empty string
